version: '2'
services:
  flask:
    image: tjshake/foosball-flask
    depends_on:
      - db
    ports:
      - "11111:11111"
    links:
      - db
    restart: always

  db:
    image: tjshake/foosball-mysql
    volumes:
      - "./.data/foosballdb:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: foosball
      MYSQL_DATABASE: foosball
      MYSQL_USER: foosball
      MYSQL_PASSWORD: foosball
